print("Hello world!")
print("Hello darkness my old friend	Not another hello world")
print("I've come to talk with you again")
print("No")
print("More")
print("Hello")
print("World")
print("Please, I'm begging you")
